theme: jekyll-theme-minimal
title: Prunelle Vogler
description: A brief description of your work
baseurl: "" # leave empty for root

# Optional configurations
author:
  name: Prunelle Vogler

# Navigation links
nav:
  - Home: /
  - CV: /cv
  - Research: /research
  - Politics: /politics
