theme: tactile
title: Prunelle Vogler
description: A brief description of your work

# Navigation links
nav:
  - Home: /
  - CV: /cv
  - Research: /research
  - Politics: /politics

github:
  is_project_page: false
