remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
title: Prunelle Vogler
description: Prunelle Vogler

# Navigation links
nav:
  - Home: /
  - CV: /cv
  - Research: /research
  - Politics: /politics

github:
  is_project_page: false
