theme: jekyll-theme-minimal
title: Your Name
description: A brief description of your work
baseurl: "" # leave empty for root

# Optional configurations
author:
  name: Your Name
  email: your-email@example.com

# Navigation links
nav:
  - Home: /
  - CV: /cv
  - Research: /research
